### ISSUE TITLE
triangle example fails due to old winit bug

### ISSUE THREAD

**Issue by joseluis** [ebkalderon/renderdoc-rs#109]
with recent versions of rust the window closes when you move the mouse over it. It's [a bug in winit 0.19](https://github.com/rust-windowing/winit/issues/1773) which is a dependency of the glutin version used in the example.

**Comment by ebkalderon** [comment]
Thanks for reporting this issue, @joseluis! Unfortunately, there's not much that can be done here because the included `triangle` example still relies on a the pre-`ll` version of `gfx`, which in turn does not support the newest version of neither `winit` nor `glutin, preventing me from upgrading. There is an open issue to port the example to `wgpu-rs` instead (#74), which is sort of like the spiritual successor to old-school `gfx`. I can try porting it over and see if it resolves the problem.

**Comment by ebkalderon** [comment]
Thanks for reporting this issue, @joseluis! Unfortunately, there's not much that can be done here because the included `triangle` example still relies on a the pre-`ll` version of `gfx`, which in turn does not support the newest version of neither `winit` nor `glutin`, preventing me from upgrading. There is an open issue to port the example to `wgpu-rs` instead (#74), which is sort of like the spiritual successor to old-school `gfx`. I can try porting it over and see if it resolves the problem.

**Comment by ebkalderon** [comment]
This crash should no longer occur now that the example is running on a modern graphics framework. Thanks again for reporting!
